/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/Client/Client`; params?: Router.UnknownInputParams; } | { pathname: `/components/Seller/Seller`; params?: Router.UnknownInputParams; } | { pathname: `/components/Products/Products`; params?: Router.UnknownInputParams; } | { pathname: `/components/Orders/Order`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/MainPage`; params?: Router.UnknownInputParams; } | { pathname: `/components/styles`; params?: Router.UnknownInputParams; } | { pathname: `/components/Footer/Footer`; params?: Router.UnknownInputParams; } | { pathname: `/components/Header/Header`; params?: Router.UnknownInputParams; } | { pathname: `/components/Home/Home`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Client/Client`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Seller/Seller`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Products/Products`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Orders/Order`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/MainPage`; params?: Router.UnknownOutputParams; } | { pathname: `/components/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Footer/Footer`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Header/Header`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Home/Home`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/components/Client/Client${`?${string}` | `#${string}` | ''}` | `/components/Seller/Seller${`?${string}` | `#${string}` | ''}` | `/components/Products/Products${`?${string}` | `#${string}` | ''}` | `/components/Orders/Order${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/MainPage${`?${string}` | `#${string}` | ''}` | `/components/styles${`?${string}` | `#${string}` | ''}` | `/components/Footer/Footer${`?${string}` | `#${string}` | ''}` | `/components/Header/Header${`?${string}` | `#${string}` | ''}` | `/components/Home/Home${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/Client/Client`; params?: Router.UnknownInputParams; } | { pathname: `/components/Seller/Seller`; params?: Router.UnknownInputParams; } | { pathname: `/components/Products/Products`; params?: Router.UnknownInputParams; } | { pathname: `/components/Orders/Order`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/MainPage`; params?: Router.UnknownInputParams; } | { pathname: `/components/styles`; params?: Router.UnknownInputParams; } | { pathname: `/components/Footer/Footer`; params?: Router.UnknownInputParams; } | { pathname: `/components/Header/Header`; params?: Router.UnknownInputParams; } | { pathname: `/components/Home/Home`; params?: Router.UnknownInputParams; };
    }
  }
}
